--=====================================================================
--                  RETAIL SALES ANALYTICS PROJECT
--=====================================================================


=====================================================================
--SECTION 1: EXECUTIVE KPI ANALYSIS
=====================================================================

--Objective:
--Provide management with an overview of the company's overall
--business performance.

--Business Questions:


--1. What is the total sales revenue generated by the company?

SELECT
    ROUND(SUM(sales),2) AS total_revenue
FROM superstore;



--2. What is the total profit earned by the company?

SELECT
    ROUND(SUM(profit),2) AS total_profit
FROM superstore;



--3. How many unique orders have been placed?

SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM superstore;



--4. How many unique customers have made purchases?

SELECT
    COUNT(DISTINCT customer_id) AS unique_customers
FROM superstore;



--5. What is the total quantity of products sold?

SELECT
    SUM(quantity) AS sold_product_quantity
FROM superstore;



--6. What is the average order value (AOV)?

SELECT
    ROUND(
        SUM(sales) / NULLIF(COUNT(DISTINCT order_id),0),
        2
    ) AS average_order_value
FROM superstore;



--7. What is the average profit generated per order?

SELECT
    ROUND(
        SUM(profit) / NULLIF(COUNT(DISTINCT order_id),0),
        2
    ) AS average_profit_per_order
FROM superstore;



--8. What is the overall profit margin (%)?

SELECT
    ROUND(
        (SUM(profit) / NULLIF(SUM(sales),0)) * 100,
        2
    ) AS profit_margin_percentage
FROM superstore;



--9. What is the average discount offered to customers?

SELECT
    ROUND(AVG(discount) * 100,2) AS average_discount_percentage
FROM superstore;




=====================================================================
--SECTION 2: SALES PERFORMANCE ANALYSIS
=====================================================================

--Objective:
--Evaluate overall sales performance over time.


--10. How have monthly sales changed over time?

SELECT
    YEAR(order_date) AS sales_year,
    MONTH(order_date) AS sales_month,
    DATENAME(MONTH,order_date) AS month_name,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    YEAR(order_date),
    MONTH(order_date),
    DATENAME(MONTH,order_date)
ORDER BY
    sales_year,
    sales_month;



--11. How has monthly profit changed over time?

SELECT
    YEAR(order_date) AS profit_year,
    MONTH(order_date) AS profit_month,
    DATENAME(MONTH,order_date) AS month_name,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    YEAR(order_date),
    MONTH(order_date),
    DATENAME(MONTH,order_date)
ORDER BY
    profit_year,
    profit_month;



--12. Which year generated the highest sales?

SELECT TOP 1
    YEAR(order_date) AS sales_year,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    YEAR(order_date)
ORDER BY
    total_sales DESC;



--13. Which year generated the highest profit?

SELECT TOP 1
    YEAR(order_date) AS profit_year,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    YEAR(order_date)
ORDER BY
    total_profit DESC;



--14. Which month recorded the highest sales?

SELECT TOP 1
    MONTH(order_date) AS sales_month,
    DATENAME(MONTH,order_date) AS month_name,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    MONTH(order_date),
    DATENAME(MONTH,order_date)
ORDER BY
    total_sales DESC;



--15. Which month recorded the lowest sales?

SELECT TOP 1
    MONTH(order_date) AS sales_month,
    DATENAME(MONTH,order_date) AS month_name,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    MONTH(order_date),
    DATENAME(MONTH,order_date)
ORDER BY
    total_sales ASC;



--16. What is the Year-over-Year (YoY) sales growth?

WITH yearly_sales AS
(
    SELECT
        YEAR(order_date) AS sales_year,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY
        YEAR(order_date)
)

SELECT
    sales_year,
    ROUND(total_sales,2) AS total_sales,

    ROUND(
        LAG(total_sales) OVER(ORDER BY sales_year),
        2
    ) AS previous_year_sales,

    ROUND(
        (
        (total_sales -
        LAG(total_sales) OVER(ORDER BY sales_year))
        /
        NULLIF(LAG(total_sales) OVER(ORDER BY sales_year),0)
        ) * 100,
        2
    ) AS yoy_sales_growth_percentage

FROM yearly_sales
ORDER BY
    sales_year;



--17. What is the Year-over-Year (YoY) profit growth?

WITH yearly_profit AS
(
    SELECT
        YEAR(order_date) AS profit_year,
        SUM(profit) AS total_profit
    FROM superstore
    GROUP BY
        YEAR(order_date)
)

SELECT
    profit_year,
    ROUND(total_profit,2) AS total_profit,

    ROUND(
        LAG(total_profit) OVER(ORDER BY profit_year),
        2
    ) AS previous_year_profit,

    ROUND(
        (
        (total_profit -
        LAG(total_profit) OVER(ORDER BY profit_year))
        /
        NULLIF(LAG(total_profit) OVER(ORDER BY profit_year),0)
        ) * 100,
        2
    ) AS yoy_profit_growth_percentage

FROM yearly_profit
ORDER BY
    profit_year;






    =====================================================================
--SECTION 3: CUSTOMER ANALYSIS
=====================================================================

--Objective:
--Identify high-value customers and understand customer behaviour.


--18. Who are the top 10 customers by sales?

SELECT TOP 10
    customer_id,
    customer_name,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    customer_id,
    customer_name
ORDER BY
    total_sales DESC;



--19. Who are the top 10 customers by profit?

SELECT TOP 10
    customer_id,
    customer_name,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    customer_id,
    customer_name
ORDER BY
    total_profit DESC;



--20. Which customer segment generates the highest revenue?

SELECT TOP 1
    segment,
    ROUND(SUM(sales),2) AS total_revenue
FROM superstore
GROUP BY
    segment
ORDER BY
    total_revenue DESC;



--21. Which customer segment generates the highest profit?

SELECT TOP 1
    segment,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    segment
ORDER BY
    total_profit DESC;



--22. What is the average spending per customer?

SELECT
    customer_id,
    customer_name,
    ROUND(
        SUM(sales) / COUNT(DISTINCT order_id),
        2
    ) AS average_customer_spending
FROM superstore
GROUP BY
    customer_id,
    customer_name
ORDER BY
    average_customer_spending DESC;



--23. Which customers have generated losses?

SELECT
    customer_id,
    customer_name,
    ROUND(SUM(profit),2) AS total_loss
FROM superstore
GROUP BY
    customer_id,
    customer_name
HAVING
    SUM(profit) < 0
ORDER BY
    total_loss ASC;




    =====================================================================
--SECTION 4: PRODUCT ANALYSIS
=====================================================================

--Objective:
--Evaluate product performance and profitability.


--24. Which are the top 10 best-selling products?

SELECT TOP 10
    product_id,
    product_name,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    product_id,
    product_name
ORDER BY
    total_sales DESC;



--25. Which are the top 10 most profitable products?

SELECT TOP 10
    product_id,
    product_name,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    product_id,
    product_name
ORDER BY
    total_profit DESC;



--26. Which products generate the highest losses?

SELECT
    product_name,
    ROUND(SUM(profit),2) AS total_loss
FROM superstore
GROUP BY
    product_name
HAVING
    SUM(profit) < 0
ORDER BY
    total_loss ASC;



--27. Which category generates the highest sales?

SELECT TOP 1
    category,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    category
ORDER BY
    total_sales DESC;



--28. Which category generates the highest profit?

SELECT TOP 1
    category,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    category
ORDER BY
    total_profit DESC;



--29. Which sub-category generates the highest sales?

SELECT TOP 1
    sub_category,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    sub_category
ORDER BY
    total_sales DESC;



--30. Which sub-category generates the highest profit?

SELECT TOP 1
    sub_category,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    sub_category
ORDER BY
    total_profit DESC;



--31. What are the top 3 products in each category?

WITH product_sales AS
(
    SELECT
        category,
        product_name,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY
        category,
        product_name
),

ranked_products AS
(
    SELECT
        category,
        product_name,
        total_sales,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY total_sales DESC
        ) AS product_rank
    FROM product_sales
)

SELECT
    category,
    product_name,
    ROUND(total_sales,2) AS total_sales,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY
    category,
    product_rank;




    =====================================================================
--SECTION 5: REGIONAL ANALYSIS
=====================================================================

--Objective:
--Identify geographical sales opportunities.


--32. Which market generates the highest sales?

SELECT TOP 1
    market,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    market
ORDER BY
    total_sales DESC;



--33. Which region generates the highest sales?

SELECT TOP 1
    region,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    region
ORDER BY
    total_sales DESC;



--34. Which country generates the highest sales?

SELECT TOP 1
    country,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    country
ORDER BY
    total_sales DESC;



--35. Which state generates the highest sales?

SELECT TOP 1
    state,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    state
ORDER BY
    total_sales DESC;



--36. Which city generates the highest sales?

SELECT TOP 1
    city,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    city
ORDER BY
    total_sales DESC;



--37. Which market is the most profitable?

SELECT TOP 1
    market,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    market
ORDER BY
    total_profit DESC;



--38. Which region is the most profitable?

SELECT TOP 1
    region,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    region
ORDER BY
    total_profit DESC;



    =====================================================================
--SECTION 6: SHIPPING & LOGISTICS ANALYSIS
=====================================================================

--Objective:
--Evaluate shipping performance.


--39. Which shipping mode is used the most?

SELECT TOP 1
    ship_mode,
    COUNT(DISTINCT order_id) AS total_orders
FROM superstore
GROUP BY
    ship_mode
ORDER BY
    total_orders DESC;



--40. Which shipping mode generates the highest sales?

SELECT TOP 1
    ship_mode,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    ship_mode
ORDER BY
    total_sales DESC;



--41. Which shipping mode generates the highest profit?

SELECT TOP 1
    ship_mode,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    ship_mode
ORDER BY
    total_profit DESC;



--42. What is the average shipping cost?

SELECT
    ROUND(AVG(shipping_cost),2) AS average_shipping_cost
FROM superstore;



--43. Which shipping mode has the highest average shipping cost?

SELECT TOP 1
    ship_mode,
    ROUND(AVG(shipping_cost),2) AS average_shipping_cost
FROM superstore
GROUP BY
    ship_mode
ORDER BY
    average_shipping_cost DESC;



    =====================================================================
--SECTION 7: DISCOUNT & PROFITABILITY ANALYSIS
=====================================================================

--Objective:
--Understand the impact of discounts on profitability.

/*=========

--44. Which category receives the highest average discount?

SELECT TOP 1
    category,
    ROUND(AVG(discount)*100,2) AS average_discount_percentage
FROM superstore
GROUP BY
    category
ORDER BY
    average_discount_percentage DESC;



--45. Which sub-category receives the highest average discount?

SELECT TOP 1
    sub_category,
    ROUND(AVG(discount)*100,2) AS average_discount_percentage
FROM superstore
GROUP BY
    sub_category
ORDER BY
    average_discount_percentage DESC;



--46. How does discount affect profit?

SELECT
    ROUND(discount*100,2) AS discount_percentage,
    ROUND(AVG(profit),2) AS average_profit,
    ROUND(SUM(profit),2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders
FROM superstore
GROUP BY
    discount
ORDER BY
    discount_percentage;



--47. Which products are sold with the highest discounts?

SELECT TOP 10
    product_name,
    ROUND(AVG(discount)*100,2) AS average_discount_percentage,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    product_name
ORDER BY
    average_discount_percentage DESC;

*/===========

--48. Which orders resulted in a loss despite high sales?

SELECT
    order_id,
    product_name,
    customer_name,
    ROUND(sales,2) AS sales,
    ROUND(profit,2) AS profit
FROM superstore
WHERE
    profit < 0
    AND sales >
    (
        SELECT AVG(sales)
        FROM superstore
    )
ORDER BY
    sales DESC;





    =====================================================================
--SECTION 8: ADVANCED SQL ANALYSIS
=====================================================================

--Objective:
--Demonstrate advanced SQL Server skills using CTEs and window functions.


--49. Rank customers by total sales.

WITH customer_sales AS
(
    SELECT
        customer_id,
        customer_name,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY
        customer_id,
        customer_name
)

SELECT
    customer_id,
    customer_name,
    ROUND(total_sales,2) AS total_sales,
    RANK() OVER(ORDER BY total_sales DESC) AS customer_rank
FROM customer_sales
ORDER BY
    customer_rank;



--50. Rank products by total profit.

WITH product_profit AS
(
    SELECT
        product_id,
        product_name,
        SUM(profit) AS total_profit
    FROM superstore
    GROUP BY
        product_id,
        product_name
)

SELECT
    product_id,
    product_name,
    ROUND(total_profit,2) AS total_profit,
    RANK() OVER(ORDER BY total_profit DESC) AS product_rank
FROM product_profit
ORDER BY
    product_rank;



--51. Find the top 3 products within each category.

WITH product_sales AS
(
    SELECT
        category,
        product_name,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY
        category,
        product_name
),

ranked_products AS
(
    SELECT
        category,
        product_name,
        total_sales,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY total_sales DESC
        ) AS product_rank
    FROM product_sales
)

SELECT
    category,
    product_name,
    ROUND(total_sales,2) AS total_sales,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY
    category,
    product_rank;



--52. Calculate cumulative monthly sales.

WITH monthly_sales AS
(
    SELECT
        YEAR(order_date) AS sales_year,
        MONTH(order_date) AS sales_month,
        SUM(sales) AS monthly_sales
    FROM superstore
    GROUP BY
        YEAR(order_date),
        MONTH(order_date)
)

SELECT
    sales_year,
    sales_month,
    ROUND(monthly_sales,2) AS monthly_sales,

    ROUND(
        SUM(monthly_sales) OVER
        (
            ORDER BY sales_year, sales_month
        ),
        2
    ) AS cumulative_sales

FROM monthly_sales
ORDER BY
    sales_year,
    sales_month;



--53. Calculate cumulative monthly profit.

WITH monthly_profit AS
(
    SELECT
        YEAR(order_date) AS profit_year,
        MONTH(order_date) AS profit_month,
        SUM(profit) AS monthly_profit
    FROM superstore
    GROUP BY
        YEAR(order_date),
        MONTH(order_date)
)

SELECT
    profit_year,
    profit_month,
    ROUND(monthly_profit,2) AS monthly_profit,

    ROUND(
        SUM(monthly_profit) OVER
        (
            ORDER BY profit_year, profit_month
        ),
        2
    ) AS cumulative_profit

FROM monthly_profit
ORDER BY
    profit_year,
    profit_month;



--54. Compare each month's sales with the previous month.

WITH monthly_sales AS
(
    SELECT
        YEAR(order_date) AS sales_year,
        MONTH(order_date) AS sales_month,
        SUM(sales) AS monthly_sales
    FROM superstore
    GROUP BY
        YEAR(order_date),
        MONTH(order_date)
)

SELECT
    sales_year,
    sales_month,
    ROUND(monthly_sales,2) AS monthly_sales,

    ROUND(
        LAG(monthly_sales) OVER
        (
            ORDER BY sales_year, sales_month
        ),
        2
    ) AS previous_month_sales,

    ROUND(
        monthly_sales -
        LAG(monthly_sales) OVER
        (
            ORDER BY sales_year, sales_month
        ),
        2
    ) AS sales_difference

FROM monthly_sales
ORDER BY
    sales_year,
    sales_month;



--55. Compare each year's sales with the previous year.

WITH yearly_sales AS
(
    SELECT
        YEAR(order_date) AS sales_year,
        SUM(sales) AS yearly_sales
    FROM superstore
    GROUP BY
        YEAR(order_date)
)

SELECT
    sales_year,
    ROUND(yearly_sales,2) AS yearly_sales,

    ROUND(
        LAG(yearly_sales) OVER
        (
            ORDER BY sales_year
        ),
        2
    ) AS previous_year_sales,

    ROUND(
        yearly_sales -
        LAG(yearly_sales) OVER
        (
            ORDER BY sales_year
        ),
        2
    ) AS sales_difference

FROM yearly_sales
ORDER BY
    sales_year;



--56. Identify the fastest-growing market.

WITH market_sales AS
(
    SELECT
        market,
        YEAR(order_date) AS sales_year,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY
        market,
        YEAR(order_date)
),

market_growth AS
(
    SELECT
        market,
        sales_year,
        total_sales,

        LAG(total_sales) OVER
        (
            PARTITION BY market
            ORDER BY sales_year
        ) AS previous_year_sales

    FROM market_sales
)

SELECT TOP 1
    market,
    sales_year,
    ROUND(total_sales,2) AS total_sales,
    ROUND(previous_year_sales,2) AS previous_year_sales,

    ROUND(
        ((total_sales - previous_year_sales)
        /
        NULLIF(previous_year_sales,0))*100,
        2
    ) AS growth_percentage

FROM market_growth
WHERE previous_year_sales IS NOT NULL
ORDER BY
    growth_percentage DESC;



--57. Identify the fastest-growing category.

WITH category_sales AS
(
    SELECT
        category,
        YEAR(order_date) AS sales_year,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY
        category,
        YEAR(order_date)
),

category_growth AS
(
    SELECT
        category,
        sales_year,
        total_sales,

        LAG(total_sales) OVER
        (
            PARTITION BY category
            ORDER BY sales_year
        ) AS previous_year_sales

    FROM category_sales
)

SELECT TOP 1
    category,
    sales_year,
    ROUND(total_sales,2) AS total_sales,
    ROUND(previous_year_sales,2) AS previous_year_sales,

    ROUND(
        ((total_sales - previous_year_sales)
        /
        NULLIF(previous_year_sales,0))*100,
        2
    ) AS growth_percentage

FROM category_growth
WHERE previous_year_sales IS NOT NULL
ORDER BY
    growth_percentage DESC;



--58. Calculate each customer's lifetime value (CLV).

SELECT
    customer_id,
    customer_name,
    ROUND(SUM(sales),2) AS lifetime_value
FROM superstore
GROUP BY
    customer_id,
    customer_name
ORDER BY
    lifetime_value DESC;



--59. What are each customer's lifetime value, total orders and average order value?

SELECT
    customer_id,
    customer_name,

    COUNT(DISTINCT order_id) AS total_orders,

    ROUND(SUM(sales),2) AS lifetime_value,

    ROUND(
        SUM(sales) /
        NULLIF(COUNT(DISTINCT order_id),0),
        2
    ) AS average_order_value

FROM superstore
GROUP BY
    customer_id,
    customer_name
ORDER BY
    lifetime_value DESC;



--60. Which products should the company discontinue due to consistent losses?

SELECT
    product_name,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    product_name
HAVING
    SUM(profit) < 0
ORDER BY
    total_profit ASC;



--61. Which regions have high sales but low profit margins?

SELECT
    region,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit,

    ROUND(
        (SUM(profit) /
        NULLIF(SUM(sales),0))*100,
        2
    ) AS profit_margin

FROM superstore
GROUP BY
    region
ORDER BY
    total_sales DESC,
    profit_margin ASC;



--62. Which product categories have the highest profit margins?

SELECT
    category,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit,

    ROUND(
        (SUM(profit) /
        NULLIF(SUM(sales),0))*100,
        2
    ) AS profit_margin

FROM superstore
GROUP BY
    category
ORDER BY
    profit_margin DESC;



--63. Which months should inventory be increased based on historical demand?

SELECT
    MONTH(order_date) AS sales_month,
    DATENAME(MONTH,order_date) AS month_name,
    SUM(quantity) AS total_quantity_sold
FROM superstore
GROUP BY
    MONTH(order_date),
    DATENAME(MONTH,order_date)
ORDER BY
    total_quantity_sold DESC;



--64. Which shipping mode offers the best balance between cost and profitability?

SELECT
    ship_mode,
    ROUND(AVG(shipping_cost),2) AS average_shipping_cost,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    ship_mode
ORDER BY
    total_profit DESC,
    average_shipping_cost ASC;



--65. Which customer segment is the most valuable based on lifetime value?

SELECT
    segment,
    ROUND(SUM(sales),2) AS customer_lifetime_value,
    ROUND(SUM(profit),2) AS total_profit,
    COUNT(DISTINCT customer_id) AS total_customers
FROM superstore
GROUP BY
    segment
ORDER BY
    customer_lifetime_value DESC;



--66. Which products should receive promotional campaigns?

SELECT TOP 10
    product_name,
    ROUND(SUM(profit),2) AS total_profit,
    ROUND(SUM(sales),2) AS total_sales
FROM superstore
GROUP BY
    product_name
ORDER BY
    total_profit DESC;



--67. Which products are frequently sold at high discounts but remain unprofitable?

SELECT
    product_name,
    ROUND(AVG(discount)*100,2) AS average_discount_percentage,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM superstore
GROUP BY
    product_name
HAVING
    AVG(discount) >= 0.20
    AND SUM(profit) < 0
ORDER BY
    average_discount_percentage DESC;